Layout/EmptyLineAfterGuardClause: {Enabled: false}
Layout/SpaceInsideHashLiteralBraces: {EnforcedStyle: no_space}
Metrics/LineLength: {Max: 100}
Style/Alias: {EnforcedStyle: prefer_alias_method}
Style/Documentation: {Enabled: false}
Style/TrailingCommaInArrayLiteral: {EnforcedStyleForMultiline: comma}
Style/TrailingCommaInHashLiteral: {EnforcedStyleForMultiline: comma}

# New cops. Need to be explicitly enabled to prevent warning.
Lint/RaiseException: {Enabled: true}
Lint/StructNewOverride: {Enabled: true}
Style/HashEachMethods: {Enabled: true}
Style/HashTransformKeys: {Enabled: true}
Style/HashTransformValues: {Enabled: true}
